[package]
name = "rust-ds-learning"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
pretty_assertions = "1.3"  # Keeping this for better test failure messages

[profile.dev]
opt-level = 0
debug = true

[profile.test]
opt-level = 0
debug = true
